'use client'

// IQAIR//OS - OTC Micro-Tick Velocity Footprint panel.
// OTC feeds are generated by a closed-loop script - there is no real order
// book, so instead of buyer/seller contracts this chart measures the
// generator's own price-print stream per price row and minute bucket:
//   left cell  = down-ticks at that level (count + avg ms between prints)
//   right cell = up-ticks at that level (count + avg ms)
// plus per-minute reads: velocity delta (up - down), speed ratio
// (down-ms / up-ms), cluster stagnation (POC density vs neighbors) and the
// divergence trap (heavy delta closing at the wrong edge of the range).
// Data source is labeled honestly on every fetch: live = the sidecar's 100ms
// price-change capture, sim = the kernel's 1s engine.
import { useCallback, useEffect, useState } from 'react'
import type { OtcFootprintBucket, OtcFootprintResult } from '@/lib/os/client'
import { fmtPrice, getOtcFootprint } from '@/lib/os/client'

interface OtcFootprintPanelProps {
  asset: string
}

const WINDOW_OPTIONS = [15, 30, 60, 120]

function fmtClockSec(t: number): string {
  const d = new Date(t * 1000)
  return `${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}:${String(d.getSeconds()).padStart(2, '0')}`
}

function DeltaBadge({ delta }: { delta: number }) {
  const pos = delta > 0
  const flat = delta === 0
  return (
    <span className={`rounded px-1 py-px font-mono text-[9px] font-bold ${flat ? 'bg-[#101828] text-[#4b5a72]' : pos ? 'bg-emerald-500/15 text-emerald-300' : 'bg-rose-500/15 text-rose-300'}`}>
      {flat ? '0' : `${pos ? '+' : ''}${delta}`} Δ
    </span>
  )
}

function Tag({ color, children, title }: { color: 'amber' | 'red' | 'emerald' | 'cyan'; children: React.ReactNode; title?: string }) {
  const cls =
    color === 'amber'
      ? 'border-amber-500/40 bg-amber-500/10 text-amber-300'
      : color === 'red'
        ? 'border-rose-500/40 bg-rose-500/10 text-rose-300'
        : color === 'emerald'
          ? 'border-emerald-500/40 bg-emerald-500/10 text-emerald-300'
          : 'border-cyan-500/40 bg-cyan-500/10 text-cyan-300'
  return (
    <span className={`rounded border px-1 py-px font-mono text-[8px] font-bold uppercase tracking-wider ${cls}`} title={title}>
      {children}
    </span>
  )
}

function BucketCard({ b, asset }: { b: OtcFootprintBucket; asset: string }) {
  const maxTotal = Math.max(...b.rows.map((r) => r.total), 1)
  const rows = b.rows.slice(0, 16) // top of the book reads better than the full ladder
  const closeIsPoc = Math.abs(b.close - b.pocPrice) < 1e-12
  return (
    <div className="rounded-lg border border-[#1c2739] bg-[#0b111c] p-2">
      <div className="flex flex-wrap items-center gap-1.5">
        <span className="font-mono text-[10px] font-bold text-[#dbe4f0]">{fmtClockSec(b.time)}</span>
        <span className="font-mono text-[9px] text-[#4b5a72]">
          O {fmtPrice(b.open, asset)} · C {fmtPrice(b.close, asset)}
        </span>
        <DeltaBadge delta={b.velDelta} />
        <span className="font-mono text-[9px] text-[#7c8aa5]" title="speed ratio: avg ms between down-ticks / up-ticks - >1 means the generator pushes UP faster">
          {b.speedRatio.toFixed(2)}:1
        </span>
        <span className="font-mono text-[9px] text-[#7c8aa5]" title="cluster stagnation: POC print density vs the median row - high = the script is looping at that level">
          stag {b.stagnation.toFixed(1)}x
        </span>
        <span className="font-mono text-[9px] text-[#4b5a72]">{b.upTicks}u/{b.dnTicks}d</span>
        {b.divergence === 'put-trap' && <Tag color="red" title="heavy positive tick delta closing at the LOW - generator ceiling cue (put)">ceiling trap</Tag>}
        {b.divergence === 'call-trap' && <Tag color="emerald" title="heavy negative tick delta closing at the HIGH - generator floor cue (call)">floor trap</Tag>}
        {b.exhaustion === 'up' && <Tag color="amber" title="up-ticks >= 3x faster than down-ticks">up thrust {b.upAvgMs.toFixed(0)}/{b.dnAvgMs.toFixed(0)}ms</Tag>}
        {b.exhaustion === 'down' && <Tag color="amber" title="down-ticks >= 3x faster than up-ticks">down thrust {b.upAvgMs.toFixed(0)}/{b.dnAvgMs.toFixed(0)}ms</Tag>}
        {closeIsPoc && <Tag color="cyan" title="the minute closed exactly on its point of control">close on POC</Tag>}
      </div>
      <div className="mt-1.5 space-y-px">
        {rows.map((r) => {
          const isPoc = r.price === b.pocPrice
          const upW = (r.up / maxTotal) * 50
          const dnW = (r.dn / maxTotal) * 50
          return (
            <div key={r.price} className="flex items-center gap-1 font-mono text-[8.5px]" title={`row ${fmtPrice(r.price, asset)}: ${r.up} up (avg ${r.upMs.toFixed(0)}ms) / ${r.dn} down (avg ${r.dnMs.toFixed(0)}ms)${r.upFast ? `, ${r.upFast} fast up` : ''}${r.dnFast ? `, ${r.dnFast} fast down` : ''}`}>
              <div className="flex h-3 flex-1 justify-end">
                {r.dn > 0 && (
                  <div className="flex h-full items-center justify-end rounded-l bg-rose-500/45 px-1 text-rose-100" style={{ width: `${Math.max(dnW, 6)}%` }}>
                    {r.dn}·{r.dnMs > 0 ? `${r.dnMs.toFixed(0)}ms` : '-'}
                  </div>
                )}
              </div>
              <div className={`w-[72px] shrink-0 text-center ${isPoc ? 'font-bold text-amber-300' : 'text-[#4b5a72]'}`}>
                {isPoc ? '★ ' : ''}
                {fmtPrice(r.price, asset)}
              </div>
              <div className="flex h-3 flex-1">
                {r.up > 0 && (
                  <div className="flex h-full items-center rounded-r bg-emerald-500/45 px-1 text-emerald-100" style={{ width: `${Math.max(upW, 6)}%` }}>
                    {r.up}·{r.upMs > 0 ? `${r.upMs.toFixed(0)}ms` : '-'}
                  </div>
                )}
              </div>
            </div>
          )
        })}
        {b.rows.length > 16 && <div className="pt-0.5 text-center font-mono text-[8px] text-[#3d4d66]">+{b.rows.length - 16} more rows</div>}
      </div>
    </div>
  )
}

export default function OtcFootprintPanel({ asset }: OtcFootprintPanelProps) {
  const [data, setData] = useState<OtcFootprintResult | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [busy, setBusy] = useState(false)
  const [minutes, setMinutes] = useState(30)

  const load = useCallback(
    (opts?: { quiet?: boolean }) => {
      if (!opts?.quiet) setBusy(true)
      getOtcFootprint(asset, { minutes, bucketSec: 60 })
        .then((d) => {
          setData(d)
          setError(null)
        })
        .catch((e: Error) => setError(e.message.slice(0, 180)))
        .finally(() => setBusy(false))
    },
    [asset, minutes],
  )

  useEffect(() => {
    load()
    const iv = setInterval(() => load({ quiet: true }), 6000)
    return () => clearInterval(iv)
  }, [load])

  const buckets = (data?.buckets ?? []).filter((b) => b.nTicks > 0).slice(-14).reverse()

  return (
    <div className="flex h-full min-h-0 flex-col">
      {/* summary strip */}
      <div className="flex flex-wrap items-center gap-2 border-b border-[#1c2739] px-3 py-1.5">
        <span className="text-[10px] font-bold uppercase tracking-wider text-cyan-300">OTC Velocity Footprint</span>
        {data && (
          <>
            <span
              className={`rounded px-1.5 py-px font-mono text-[9px] font-bold uppercase ${
                data.summary.signal === 'call'
                  ? 'bg-emerald-500/20 text-emerald-300'
                  : data.summary.signal === 'put'
                    ? 'bg-rose-500/20 text-rose-300'
                    : 'bg-[#101828] text-[#4b5a72]'
              }`}
              title={data.summary.note}
            >
              {data.summary.signal} {data.summary.score > 0 ? data.summary.score : ''}
            </span>
            <span className="font-mono text-[9px] text-[#7c8aa5]" title="velocity delta over the window (up-ticks - down-ticks)">
              Δ {data.summary.netDelta >= 0 ? '+' : ''}
              {data.summary.netDelta} ({data.summary.totalUp}u/{data.summary.totalDn}d)
            </span>
            <span className="font-mono text-[9px] text-[#7c8aa5]" title="average speed ratio across buckets - 1.0 = symmetric">
              ratio {data.summary.avgSpeedRatio.toFixed(2)}:1
            </span>
            {data.summary.dominantPoc > 0 && (
              <span className="font-mono text-[9px] text-amber-300/90" title="most repeated point of control across the window">
                POC {fmtPrice(data.summary.dominantPoc, asset)}
              </span>
            )}
            <span
              className="rounded border border-amber-500/30 bg-amber-500/10 px-1 py-px font-mono text-[8px] uppercase text-amber-400"
              title={`${data.dataSource}${data.cadenceMs !== null ? `, median inter-tick gap ${data.cadenceMs}ms` : ''} - measured print cadence is upper-bounded by the capture rate`}
            >
              {data.dataSource}
              {data.cadenceMs !== null ? ` · ${data.cadenceMs}ms` : ''}
            </span>
          </>
        )}
        <div className="ml-auto flex items-center gap-1">
          <select
            value={minutes}
            onChange={(e) => setMinutes(Number(e.target.value))}
            className="h-6 rounded border border-[#1c2739] bg-[#101828] px-1 font-mono text-[9px] text-[#dbe4f0]"
            title="window length ending now"
          >
            {WINDOW_OPTIONS.map((m) => (
              <option key={m} value={m}>
                {m}m
              </option>
            ))}
          </select>
          <button
            type="button"
            onClick={() => load()}
            className="rounded border border-[#1c2739] px-2 py-0.5 font-mono text-[9px] uppercase text-[#7c8aa5] hover:text-cyan-300"
          >
            {busy ? '…' : 'refresh'}
          </button>
        </div>
      </div>

      <div className="min-h-0 flex-1 overflow-auto p-2">
        {error && <div className="p-3 text-[10px] text-rose-400">{error}</div>}
        {!error && (!data || data.buckets.length === 0) && (
          <div className="p-3 text-[10px] leading-relaxed text-[#4b5a72]">
            No micro-tick prints captured for {asset} yet. The collector records the feed&apos;s price CHANGES - sim feeds tick every ~1s, live OTC
            via the sidecar&apos;s 100ms capture. Wait a minute or two; the footprint (and the OTC velocity strategy + lab features) build from the
            same buffer.
          </div>
        )}
        {data && data.buckets.length > 0 && buckets.length === 0 && (
          <div className="p-3 text-[10px] text-[#4b5a72]">Ticks captured but no prints landed in the window yet - widen the window.</div>
        )}
        <div className="grid grid-cols-1 gap-2 lg:grid-cols-2 2xl:grid-cols-3">
          {buckets.map((b) => (
            <BucketCard key={b.time} b={b} asset={asset} />
          ))}
        </div>
        {data && (
          <p className="mt-2 px-1 text-[9px] leading-relaxed text-[#4b5a72]">
            Reads the generator&apos;s hand, not volume: left cell = down-ticks at that level (count · avg ms between prints), right = up-ticks. A
            level with prints several times denser than its neighbors is the ★ POC - the script looping there. Fast one-sided thrusts that close at
            the wrong edge of their range (ceiling/floor traps) are the blueprint&apos;s divergence cue; the same metrics feed the
            <span className="text-[#aab6cc]"> OTC Velocity Footprint</span> builtin strategy and the lab&apos;s otcv* signal family.
          </p>
        )}
      </div>
    </div>
  )
}
