// IQAIR//OS - Synthetic OTC Micro-Tick Velocity Footprint
// OTC charts are generated by a closed-loop algorithmic script - there is no
// real order book, no real volume, no bid/ask tags. Traditional volume
// footprint charts measure contracts at price levels; none of that exists
// here. What DOES exist is the generator's own price-print stream, and its
// timing leaks the generator's hand:
//
//   - how FAST it ticks up vs down through a price level (velocity asymmetry)
//   - how many up vs down prints a minute prints (tick delta) and where the
//     minute CLOSES relative to that delta (the divergence trap: heavy
//     positive delta closing at the low = a structural ceiling in the
//     generator's code - the classic put cue, mirrored for calls)
//   - where prints CLUSTER (a level taking an order of magnitude more prints
//     than its neighbors = the script looping/consolidating there - the OTC
//     analog of a Point of Control)
//
// HONESTY: measured cadence is upper-bounded by the capture rate. Live OTC
// ticks come from the sidecar's 100ms RAM-table poller (records on price
// CHANGE, wall-clock timestamp); sim ticks are the 1s kernel engine. The
// result carries `dataSource` + median inter-tick cadence so the UI can
// label exactly what was measured, never implying true exchange ticks.

import type { Candle } from '../types'

export interface TickPoint {
  ts: number // epoch MILLISECONDS
  price: number
}

// ---------- tick provider (kernel plugin registers itself here) ----------

let tickProvider: ((asset: string) => TickPoint[]) | null = null

/** The kernel's footprint plugin registers a provider at boot; pure callers
 * (strategies, lab indicator series) read through `ticksFor` so they never
 * depend on plugin wiring. */
export function registerTickProvider(fn: (asset: string) => TickPoint[]): void {
  tickProvider = fn
}

/** Micro-tick buffer for an asset (empty when the collector hasn't covered
 * it yet - callers must treat that as "stand aside", never fabricate). */
export function ticksFor(asset: string): TickPoint[] {
  try {
    return tickProvider ? tickProvider(asset) : []
  } catch {
    return []
  }
}

// ---------- footprint build ----------

export interface FootprintRow {
  price: number
  up: number // up-ticks landing at this level
  dn: number // down-ticks landing at this level
  upMs: number // avg ms since the previous tick, up-ticks (0 when none)
  dnMs: number // avg ms since the previous tick, down-ticks
  upFast: number // up-ticks faster than fastMs
  dnFast: number // down-ticks faster than fastMs
  total: number
}

export interface FootprintBucket {
  time: number // epoch SECONDS (bucket start)
  open: number
  high: number
  low: number
  close: number
  nTicks: number
  upTicks: number
  dnTicks: number
  upAvgMs: number
  dnAvgMs: number
  /** dnAvgMs / upAvgMs - >1 means the generator is moving UP through these
   * levels faster (aggressive up-thrust), <1 the mirror. 1 = symmetric. */
  speedRatio: number
  /** upTicks - dnTicks. Metric B: the velocity delta. */
  velDelta: number
  rows: FootprintRow[] // sorted high price -> low
  pocPrice: number
  pocTicks: number
  /** pocTicks / median(row totals) - Metric C: cluster stagnation. ~1 = the
   * level is ordinary; >= 3 = the script is looping at that exact price. */
  stagnation: number
  /** (close - low) / range, 0..1 - where the minute closed in its range */
  closePos: number
  /** Metric B divergence trap: heavy positive delta closing at the low
   * (generator ceiling -> put), or heavy negative delta closing at the
   * high (floor -> call). */
  divergence: 'put-trap' | 'call-trap' | null
  /** speed-ratio exhaustion: one side ticking >= ratioAt times faster while
   * the OTHER side still has prints (a genuine thrust, not a one-way gap) */
  exhaustion: 'up' | 'down' | null
}

export interface FootprintResult {
  asset: string
  bucketSec: number
  tickSize: number
  /** 'sidecar-tick-100ms' (live OTC) | 'sim-tick-1s' | 'kernel-tick-buffer' */
  dataSource: string
  /** median inter-tick gap in the window - the honest resolution label */
  cadenceMs: number | null
  minutes: number
  buckets: FootprintBucket[] // oldest -> newest (incomplete trailing bucket included)
  summary: {
    totalUp: number
    totalDn: number
    netDelta: number
    avgSpeedRatio: number
    dominantPoc: number
    signal: 'call' | 'put' | 'none'
    score: number
    note: string
  }
}

export interface FootprintOpts {
  bucketSec?: number
  minutes?: number
  tickSize?: number
  /** "high velocity" threshold in ms - default 150 because the live capture
   * poller runs at 100ms, so anything under that is at capture resolution */
  fastMs?: number
  minDelta?: number // divergence threshold on |up - dn| (default 3)
  ratioAt?: number // speed-ratio exhaustion threshold (default 3)
  stagnationAt?: number // stagnation "looping" threshold (default 3)
  nowMs?: number
  /** honesty label for the capture source, set by the kernel plugin */
  dataSourceLabel?: string
}

/** Derive the row grid: smallest observed positive price delta, quantized
 * down to a sane power-of-ten-ish step so float noise never splits rows. */
function deriveTickSize(ticks: TickPoint[]): number {
  let min = Infinity
  for (let i = 1; i < ticks.length; i++) {
    const d = Math.abs(ticks[i].price - ticks[i - 1].price)
    if (d > 1e-12 && d < min) min = d
  }
  if (!Number.isFinite(min)) return 1e-5
  // snap to 1-2-5 x 10^k so rows stay human-readable
  const pow = Math.pow(10, Math.floor(Math.log10(min)))
  const m = min / pow
  const step = m >= 5 ? 5 : m >= 2 ? 2 : 1
  return step * pow
}

function median(arr: number[]): number {
  if (!arr.length) return 0
  const s = [...arr].sort((a, b) => a - b)
  const mid = s.length >> 1
  return s.length % 2 ? s[mid] : (s[mid - 1] + s[mid]) / 2
}

/** Build the velocity footprint: group ticks into time buckets, split every
 * print by direction (vs the previous print's price, ACROSS bucket edges -
 * the first print of a bucket still has a direction), and measure each
 * level's up/down speed + density. */
export function buildFootprint(ticks: TickPoint[], opts: FootprintOpts & { asset?: string } = {}): FootprintResult {
  const bucketSec = Math.max(5, Math.round(opts.bucketSec ?? 60))
  const minutes = Math.max(1, Math.round(opts.minutes ?? 30))
  const fastMs = Math.max(1, opts.fastMs ?? 150)
  const minDelta = Math.max(1, Math.round(opts.minDelta ?? 3))
  const ratioAt = Math.max(1.5, opts.ratioAt ?? 3)
  const stagnationAt = Math.max(1.5, opts.stagnationAt ?? 3)
  const nowMs = opts.nowMs ?? Date.now()
  const windowStart = nowMs - minutes * 60_000
  const win = ticks.filter((t) => t.ts >= windowStart && t.ts <= nowMs + 5_000)

  const tickSize = opts.tickSize && opts.tickSize > 0 ? opts.tickSize : deriveTickSize(win)
  const rowKey = (p: number) => Math.round(p / tickSize)

  // median cadence over the window (honesty label)
  const gaps: number[] = []
  for (let i = 1; i < win.length; i++) {
    const g = win[i].ts - win[i - 1].ts
    if (g >= 0) gaps.push(g)
  }
  const cadenceMs = gaps.length ? Math.round(median(gaps)) : null

  const buckets: FootprintBucket[] = []
  let prev: TickPoint | null = null
  let cur: { start: number; rows: Map<number, FootprintRow>; first: number; last: number; hi: number; lo: number; n: number; up: number; dn: number; upMsSum: number; dnMsSum: number } | null = null

  const flush = () => {
    if (!cur || !prev) return
    const rows = [...cur.rows.values()].sort((a, b) => b.price - a.price)
    const poc = rows.reduce((best, r) => (r.total > best.total ? r : best), rows[0])
    const med = median(rows.map((r) => r.total))
    const range = Math.max(cur.hi - cur.lo, 1e-12)
    const upAvg = cur.up ? cur.upMsSum / cur.up : 0
    const dnAvg = cur.dn ? cur.dnMsSum / cur.dn : 0
    const velDelta = cur.up - cur.dn
    const closePos = (cur.last - cur.lo) / range
    const ratio = upAvg > 0 ? dnAvg / upAvg : dnAvg > 0 ? ratioAt * 2 : 1
    const divergence: FootprintBucket['divergence'] =
      velDelta >= minDelta && closePos <= 0.25 ? 'put-trap' : velDelta <= -minDelta && closePos >= 0.75 ? 'call-trap' : null
    const exhaustion: FootprintBucket['exhaustion'] =
      ratio >= ratioAt && cur.up >= 2 && cur.dn >= 1 ? 'up' : ratio <= 1 / ratioAt && cur.dn >= 2 && cur.up >= 1 ? 'down' : null
    buckets.push({
      time: cur.start,
      open: cur.first,
      high: cur.hi,
      low: cur.lo,
      close: cur.last,
      nTicks: cur.n,
      upTicks: cur.up,
      dnTicks: cur.dn,
      upAvgMs: Math.round(upAvg * 10) / 10,
      dnAvgMs: Math.round(dnAvg * 10) / 10,
      speedRatio: Math.round(ratio * 100) / 100,
      velDelta,
      rows,
      pocPrice: poc.price,
      pocTicks: poc.total,
      stagnation: Math.round((poc.total / Math.max(med, 1)) * 100) / 100,
      closePos: Math.round(closePos * 1000) / 1000,
      divergence,
      exhaustion,
    })
  }

  for (const t of win) {
    const start = Math.floor(t.ts / 1000 / bucketSec) * bucketSec
    if (!cur || cur.start !== start) {
      flush()
      cur = { start, rows: new Map(), first: t.price, last: t.price, hi: t.price, lo: t.price, n: 0, up: 0, dn: 0, upMsSum: 0, dnMsSum: 0 }
    }
    const k = rowKey(t.price)
    let row = cur.rows.get(k)
    if (!row) {
      row = { price: k * tickSize, up: 0, dn: 0, upMs: 0, dnMs: 0, upFast: 0, dnFast: 0, total: 0 }
      cur.rows.set(k, row)
    }
    cur.last = t.price
    cur.hi = Math.max(cur.hi, t.price)
    cur.lo = Math.min(cur.lo, t.price)
    cur.n += 1
    row.total += 1
    if (prev) {
      const gap = Math.max(0, t.ts - prev.ts)
      if (t.price > prev.price) {
        cur.up += 1
        cur.upMsSum += gap
        row.up += 1
        row.upMs += gap
        if (gap <= fastMs) row.upFast += 1
      } else if (t.price < prev.price) {
        cur.dn += 1
        cur.dnMsSum += gap
        row.dn += 1
        row.dnMs += gap
        if (gap <= fastMs) row.dnFast += 1
      }
    }
    prev = t
  }
  flush()

  const totalUp = buckets.reduce((s, b) => s + b.upTicks, 0)
  const totalDn = buckets.reduce((s, b) => s + b.dnTicks, 0)
  const withTicks = buckets.filter((b) => b.nTicks > 0)
  const avgSpeedRatio = withTicks.length ? withTicks.reduce((s, b) => s + b.speedRatio, 0) / withTicks.length : 1
  const pocCounts = new Map<number, number>()
  for (const b of withTicks) pocCounts.set(b.pocPrice, (pocCounts.get(b.pocPrice) ?? 0) + b.pocTicks)
  const dominantPoc = [...pocCounts.entries()].sort((a, b) => b[1] - a[1])[0]?.[0] ?? 0

  // window-level read: weigh the last few COMPLETED signals, prefer the
  // freshest divergence, then exhaustion, then stagnation fade
  let signal: 'call' | 'put' | 'none' = 'none'
  let score = 0
  let note = 'no footprint edge in the window'
  const recent = withTicks.slice(-3).reverse() // newest first
  const div = recent.find((b) => b.divergence)
  if (div) {
    signal = div.divergence === 'put-trap' ? 'put' : 'call'
    score = 62 + Math.min(18, Math.abs(div.velDelta) * 2) + (div.stagnation >= stagnationAt ? 6 : 0)
    note = `${div.divergence === 'put-trap' ? 'positive' : 'negative'} tick delta (${div.velDelta >= 0 ? '+' : ''}${div.velDelta}) closing at the ${div.divergence === 'put-trap' ? 'low' : 'high'} in the ${fmtAge(div.time, nowMs)} bucket - generator ${div.divergence === 'put-trap' ? 'ceiling' : 'floor'} cue`
  } else {
    const exh = recent.find((b) => b.exhaustion)
    if (exh) {
      // exhaustion fades the thrust once it stops converting to range
      const fadeDown = exh.exhaustion === 'up' && exh.closePos <= 0.4
      const fadeUp = exh.exhaustion === 'down' && exh.closePos >= 0.6
      if (fadeDown || fadeUp) {
        signal = fadeDown ? 'put' : 'call'
        score = 58 + Math.min(14, (Math.max(exh.speedRatio, 1 / Math.max(exh.speedRatio, 1e-9)) - 1) * 8)
        note = `${exh.exhaustion}-side velocity exhaustion (${exh.speedRatio.toFixed(2)}:1 speed ratio) fading - thrust not converting to range in the ${fmtAge(exh.time, nowMs)} bucket`
      }
    }
    if (signal === 'none') {
      const stag = recent.find((b) => b.stagnation >= stagnationAt)
      if (stag) {
        signal = stag.close > stag.pocPrice ? 'put' : 'call'
        score = 55 + Math.min(12, (stag.stagnation - 1) * 4)
        note = `cluster stagnation ${stag.stagnation.toFixed(1)}x at ${stag.pocPrice.toPrecision(6)} - script looping at the ${stag.close > stag.pocPrice ? 'top' : 'bottom'} of the loop, fading the edge`
      }
    }
  }
  score = Math.round(Math.max(0, Math.min(95, score)))

  return {
    asset: opts.asset ?? '',
    bucketSec,
    tickSize,
    dataSource: opts.dataSourceLabel ?? 'kernel-tick-buffer',
    // (dataSourceLabel is set by the kernel plugin; pure callers get the
    // generic label so charts can still distinguish sources upstream)
    cadenceMs,
    minutes,
    buckets,
    summary: {
      totalUp,
      totalDn,
      netDelta: totalUp - totalDn,
      avgSpeedRatio: Math.round(avgSpeedRatio * 100) / 100,
      dominantPoc,
      signal,
      score,
      note,
    },
  }
}

function fmtAge(bucketSec: number, nowMs: number): string {
  const mins = Math.max(0, Math.round((nowMs / 1000 - bucketSec) / 60))
  return mins <= 1 ? 'latest' : `-${mins}m`
}

// ---------- per-candle velocity series (AI lab / backtests) ----------

export interface VelocitySeries {
  /** per-candle tick delta (up - dn) of the matching minute bucket; NaN
   * where the tick buffer has no coverage for that bar's bucket */
  vdelta: number[]
  /** per-candle speed ratio (dnAvgMs/upAvgMs, log2-signed so it is symmetric
   * around 0); NaN uncovered */
  vratio: number[]
  /** per-candle cluster stagnation (poc/median); NaN uncovered */
  stagn: number[]
  /** number of candles with real tick coverage */
  covered: number
}

/** Map the tick buffer onto a candle series by bucket time - the exact
 * per-bar feature read the lab mines and the live evaluator replays. The
 * bucket grid follows the candles' own spacing (1m candles -> 1m buckets,
 * 5m -> 5m) so every bar reads exactly the prints inside its window. Bars
 * whose bucket has fewer than 3 prints stay NaN (signal never fires there -
 * honest coverage, no fabrication). */
export function velocitySeriesFor(candles: Candle[], ticks: TickPoint[], bucketSec?: number): VelocitySeries {
  // candle spacing = the bucket grid (min positive delta is robust to gaps)
  if (!bucketSec || bucketSec <= 0) {
    let minGap = Infinity
    for (let i = 1; i < candles.length; i++) {
      const g = candles[i].time - candles[i - 1].time
      if (g > 0 && g < minGap) minGap = g
    }
    bucketSec = Number.isFinite(minGap) ? minGap : 60
  }
  const rowSize = deriveTickSize(ticks)
  const byBucket = new Map<number, TickPoint[]>()
  for (const t of ticks) {
    const b = Math.floor(t.ts / 1000 / bucketSec) * bucketSec
    const arr = byBucket.get(b)
    if (arr) arr.push(t)
    else byBucket.set(b, [t])
  }
  const vdelta = new Array<number>(candles.length).fill(NaN)
  const vratio = new Array<number>(candles.length).fill(NaN)
  const stagn = new Array<number>(candles.length).fill(NaN)
  let covered = 0
  for (let i = 0; i < candles.length; i++) {
    const b = Math.floor(candles[i].time / bucketSec) * bucketSec
    const arr = byBucket.get(b)
    if (!arr || arr.length < 3) continue
    let up = 0
    let dn = 0
    let upMs = 0
    let dnMs = 0
    const rows = new Map<number, number>()
    for (let j = 1; j < arr.length; j++) {
      const gap = Math.max(0, arr[j].ts - arr[j - 1].ts)
      const key = Math.round(arr[j].price / rowSize)
      rows.set(key, (rows.get(key) ?? 0) + 1)
      if (arr[j].price > arr[j - 1].price) {
        up++
        upMs += gap
      } else if (arr[j].price < arr[j - 1].price) {
        dn++
        dnMs += gap
      }
    }
    if (up + dn === 0) continue
    const upAvg = up ? upMs / up : 0
    const dnAvg = dn ? dnMs / dn : 0
    const ratio = upAvg > 0 ? dnAvg / upAvg : dnAvg > 0 ? 8 : 1
    const totals = [...rows.values()].sort((a, b) => a - b)
    const med = totals.length ? (totals.length % 2 ? totals[(totals.length - 1) >> 1] : (totals[totals.length / 2 - 1] + totals[totals.length / 2]) / 2) : 1
    const poc = Math.max(...rows.values())
    vdelta[i] = up - dn
    vratio[i] = Math.log2(Math.max(ratio, 1 / 8))
    stagn[i] = poc / Math.max(med, 1)
    covered++
  }
  return { vdelta, vratio, stagn, covered }
}

// ---------- builtin strategy core ----------

export interface VelocitySignalOpts {
  minDelta?: number
  ratioAt?: number
  stagnationAt?: number
  nearEdge?: number // closePos threshold for the divergence trap (default 0.25)
}

export interface VelocitySignal {
  direction: 'call' | 'put' | 'none'
  score: number
  notes: string
  metrics: {
    upTicks: number
    dnTicks: number
    velDelta: number
    speedRatio: number
    stagnation: number
    closePos: number
    pocPrice: number
    ticksCovered: number
  } | null
}

/** The OTC velocity trade logic, shared by the builtin strategy: read the
 * newest COMPLETE minute bucket (plus the forming one for context), fire on
 * divergence > exhaustion-fade > stagnation-fade, stand aside otherwise. */
export function otcVelocitySignal(ticks: TickPoint[], opts: VelocitySignalOpts & { nowMs?: number } = {}): VelocitySignal {
  const minDelta = Math.max(1, Math.round(opts.minDelta ?? 3))
  const ratioAt = Math.max(1.5, opts.ratioAt ?? 3)
  const stagnationAt = Math.max(1.5, opts.stagnationAt ?? 3)
  const nearEdge = Math.max(0.05, Math.min(0.45, opts.nearEdge ?? 0.25))
  if (ticks.length < 30) {
    return { direction: 'none', score: 0, notes: `micro-tick buffer warming up (${ticks.length}/30 ticks)`, metrics: null }
  }
  const nowMs = opts.nowMs ?? Date.now()
  const fp = buildFootprint(ticks, { bucketSec: 60, minutes: 10, minDelta, ratioAt, stagnationAt, nowMs })
  // only FULLY CLOSED minute buckets trade - the forming bucket's metrics
  // would leak the future into a backtest and mismatch the per-candle
  // velocity series the lab mines (bar T's feature = bucket T, known at T+60)
  const nowSec = Math.floor(nowMs / 1000)
  const complete = fp.buckets.filter((b) => b.nTicks >= 3 && b.time + fp.bucketSec <= nowSec)
  const b = complete[complete.length - 1]
  if (!b) {
    return { direction: 'none', score: 0, notes: 'no completed minute bucket with enough prints yet', metrics: null }
  }
  const metrics = {
    upTicks: b.upTicks,
    dnTicks: b.dnTicks,
    velDelta: b.velDelta,
    speedRatio: b.speedRatio,
    stagnation: b.stagnation,
    closePos: b.closePos,
    pocPrice: b.pocPrice,
    ticksCovered: ticks.length,
  }
  // 1) the divergence trap (Metric B) - the blueprint's headline cue
  if (b.divergence === 'put-trap' || (b.velDelta >= minDelta && b.closePos <= nearEdge * 2)) {
    return {
      direction: 'put',
      score: Math.min(94, Math.round(60 + Math.min(20, Math.abs(b.velDelta) * 2) + (b.stagnation >= stagnationAt ? 8 : 0))),
      notes: `vel delta ${b.velDelta >= 0 ? '+' : ''}${b.velDelta} (${b.upTicks}u/${b.dnTicks}d) closed at ${Math.round(b.closePos * 100)}% of range - generator ceiling`,
      metrics,
    }
  }
  if (b.divergence === 'call-trap' || (b.velDelta <= -minDelta && b.closePos >= 1 - nearEdge * 2)) {
    return {
      direction: 'call',
      score: Math.min(94, Math.round(60 + Math.min(20, Math.abs(b.velDelta) * 2) + (b.stagnation >= stagnationAt ? 8 : 0))),
      notes: `vel delta ${b.velDelta} (${b.upTicks}u/${b.dnTicks}d) closed at ${Math.round(b.closePos * 100)}% of range - generator floor`,
      metrics,
    }
  }
  // 2) velocity exhaustion fading (Metric A) - thrust not converting to range
  if (b.exhaustion === 'up' && b.closePos <= 0.4) {
    return {
      direction: 'put',
      score: Math.min(88, Math.round(56 + Math.min(16, (b.speedRatio - 1) * 8))),
      notes: `up-thrust ${b.speedRatio.toFixed(2)}:1 (${b.upAvgMs.toFixed(0)}ms vs ${b.dnAvgMs.toFixed(0)}ms) fading at ${Math.round(b.closePos * 100)}% of range`,
      metrics,
    }
  }
  if (b.exhaustion === 'down' && b.closePos >= 0.6) {
    return {
      direction: 'call',
      score: Math.min(88, Math.round(56 + Math.min(16, (1 / Math.max(b.speedRatio, 1e-9) - 1) * 8))),
      notes: `down-thrust ${b.speedRatio.toFixed(2)}:1 (${b.upAvgMs.toFixed(0)}ms vs ${b.dnAvgMs.toFixed(0)}ms) fading at ${Math.round(b.closePos * 100)}% of range`,
      metrics,
    }
  }
  // 3) cluster stagnation fade (Metric C) - script looping at a level
  if (b.stagnation >= stagnationAt) {
    const dir: 'call' | 'put' = b.close > b.pocPrice ? 'put' : 'call'
    return {
      direction: dir,
      score: Math.min(85, Math.round(55 + Math.min(14, (b.stagnation - 1) * 4))),
      notes: `stagnation ${b.stagnation.toFixed(1)}x at ${b.pocPrice.toPrecision(6)} (${b.pocTicks} prints) - looping ${dir === 'put' ? 'below' : 'above'} price, fading`,
      metrics,
    }
  }
  return {
    direction: 'none',
    score: 0,
    notes: `delta ${b.velDelta >= 0 ? '+' : ''}${b.velDelta}, ratio ${b.speedRatio.toFixed(2)}, stagnation ${b.stagnation.toFixed(1)} - no OTC footprint edge`,
    metrics,
  }
}
